Repository FACK1/ReWorks, pull requests merged in 2019-04, with the labels that each got.

#136 CSV Export
  client/package-lock.json
  client/src/components/ItemList/index.js
  client/src/components/ItemList/itemlist.style.js
  client/src/components/Shared/Button/button.style.js
  client/src/components/Shared/Button/index.js
  client/src/components/SplashPage/splashpage.style.js
  package-lock.json
  package.json
Labels: awaiting-review

#215 Add Clarifai's types as new types in airtable: issue #214
  client/src/components/GetDetails/index.js
  server/controllers/addType.js
  server/router.js
Labels: technical

#197 Desktop
  client/src/components/Feedback/feedback.style.js
  client/src/components/Feedback/index.js
  client/src/components/GetDetails/getdetails.style.js
  client/src/components/GetDetails/index.js
  client/src/components/Item/item.style.js
  client/src/components/ItemList/index.js
  client/src/components/ItemList/itemlist.style.js
  client/src/components/Login/index.js
  client/src/components/Login/login.style.js
  client/src/components/Shared/Button/button.style.js
  client/src/components/Shared/Footer/footer.style.js
  client/src/components/Shared/Form/form.style.js
  client/src/components/Shared/GreenButton/greenbutton.style.js
  client/src/components/Shared/Spinner/spinner.style.js
  client/src/components/Shared/Title/title.style.js
  client/src/components/SignUp/index.js
  client/src/components/SignUp/signup.style.js
  client/src/components/SplashPage/splashpage.style.js
  client/src/components/Upload/upload.style.js
  package-lock.json
Labels: BLOCKED
